trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  Major: 4
  Minor: 0
  BuildConfiguration: 'Release'

name: $(Major).$(Minor).$(BuildID)

steps:
- checkout: self
  submodules: true

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.401'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    feedsToUse: 'select'
    versioningScheme: byBuildNumber
    arguments: '--configuration $(BuildConfiguration) -p:Version=$(Build.BuildNumber);FileVersion=$(Build.BuildNumber)'

- task: CmdLine@2
  inputs:
    script: 'iscc /Q "Setup Script.iss"'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'ServerStaging'
    ArtifactName: 'artifact'
    publishLocation: 'Container'    